# Creating Arrays

In [1]:
import numpy as np

In [2]:
one_d = np.array([1,2,3])
one_d

array([1, 2, 3])

Sometimes we just want to create an array with a given shape. We can do this using the `ones`, `zeros`, `arange`

In [3]:
ones = np.ones((2,3,3), dtype=str)
ones

array([[['1', '1', '1'],
        ['1', '1', '1'],
        ['1', '1', '1']],

       [['1', '1', '1'],
        ['1', '1', '1'],
        ['1', '1', '1']]], dtype='<U1')

In [4]:
array_from_range = np.arange(0, 20, 3)
array_from_range

array([ 0,  3,  6,  9, 12, 15, 18])

In [5]:
array_with_random_ints = np.random.randint(1, 100, (5,4))
array_with_random_ints

array([[79, 34, 51, 17],
       [73, 43, 83, 36],
       [60, 96, 80, 92],
       [79, 89, 48, 27],
       [44, 51, 87, 29]])

In [6]:
array_with_random_floats = np.random.random((6,3))
array_with_random_floats

array([[0.90437567, 0.22028631, 0.72788259],
       [0.7913316 , 0.31966372, 0.58556257],
       [0.22827483, 0.88165549, 0.52483884],
       [0.09496781, 0.76239879, 0.31752114],
       [0.64415386, 0.85145683, 0.17401625],
       [0.82328818, 0.95793898, 0.86793474]])

Give all this randomness, we might want to share our notebook and allow people to rerun the cells with the same random values we got. It turns out that numpy's random numbers are not really random but `pseudo random numbers` which means that we have specify a `seed` number and numpy will stick to that seed rather than picking a different seed everytime.

In [7]:
np.random.seed(5)
random_ints = np.random.randint(1, 100, (5,4))
random_ints

array([[79, 62, 17, 74],
       [ 9, 63, 28, 31],
       [81,  8, 77, 16],
       [54, 81, 28, 45],
       [78, 76, 66, 48]])

As you can see, the above random array generator doesn't change while the array generator below keeps changing everytime the cell is rerun.

In [8]:
random_ints = np.random.randint(1, 100, (5,4))
random_ints

array([[31, 85, 87, 19],
       [10, 42, 63,  2],
       [83, 17, 79,  6],
       [59,  1, 81,  5],
       [37, 52, 28, 32]])