# Viewing Arrays and Matrices

In [1]:
import numpy as np

In [3]:
three_dimensional = np.array([
    [
        [15.5, 20, 44],
        [34, 23, 78.2],
        [43, 64.3, 76]
    ],
    [
        [24, 24, 24],
        [80, 69, 32],
        [12, 15, 19]
    ]
])

In [4]:
np.unique(three_dimensional).size

16

In [5]:
three_dimensional.size

18

In [6]:
three_dimensional

array([[[15.5, 20. , 44. ],
        [34. , 23. , 78.2],
        [43. , 64.3, 76. ]],

       [[24. , 24. , 24. ],
        [80. , 69. , 32. ],
        [12. , 15. , 19. ]]])

In [7]:
three_dimensional[0]

array([[15.5, 20. , 44. ],
       [34. , 23. , 78.2],
       [43. , 64.3, 76. ]])

In [8]:
three_dimensional[:2, :2]

array([[[15.5, 20. , 44. ],
        [34. , 23. , 78.2]],

       [[24. , 24. , 24. ],
        [80. , 69. , 32. ]]])

In [9]:
random_sized_array = np.random.randint(10, size=(2,3,4,5))
random_sized_array

array([[[[6, 5, 6, 1, 6],
         [9, 7, 7, 0, 6],
         [9, 8, 1, 0, 7],
         [7, 1, 4, 2, 0]],

        [[8, 2, 0, 9, 6],
         [4, 1, 6, 1, 8],
         [9, 0, 8, 8, 7],
         [5, 7, 7, 9, 8]],

        [[7, 9, 7, 0, 4],
         [5, 7, 1, 3, 4],
         [3, 4, 3, 0, 6],
         [4, 6, 0, 5, 4]]],


       [[[9, 7, 0, 3, 3],
         [3, 1, 3, 9, 6],
         [3, 7, 9, 9, 5],
         [9, 6, 2, 4, 4]],

        [[5, 2, 7, 7, 9],
         [8, 0, 5, 2, 5],
         [3, 1, 4, 4, 0],
         [7, 6, 0, 1, 1]],

        [[1, 3, 1, 7, 1],
         [4, 3, 2, 1, 0],
         [3, 6, 3, 5, 6],
         [7, 0, 7, 9, 4]]]])

In [10]:
random_sized_array.shape, random_sized_array.ndim

((2, 3, 4, 5), 4)

In [11]:
random_sized_array[:,:,:,:3]

array([[[[6, 5, 6],
         [9, 7, 7],
         [9, 8, 1],
         [7, 1, 4]],

        [[8, 2, 0],
         [4, 1, 6],
         [9, 0, 8],
         [5, 7, 7]],

        [[7, 9, 7],
         [5, 7, 1],
         [3, 4, 3],
         [4, 6, 0]]],


       [[[9, 7, 0],
         [3, 1, 3],
         [3, 7, 9],
         [9, 6, 2]],

        [[5, 2, 7],
         [8, 0, 5],
         [3, 1, 4],
         [7, 6, 0]],

        [[1, 3, 1],
         [4, 3, 2],
         [3, 6, 3],
         [7, 0, 7]]]])