# Exercise Pandas and Numpy

We have a DataFrame for our number of sales of goods (Gameboy, Wii, Switch) and a DataFrame for the price for each one of these goods.

In [3]:
import pandas as pd
import numpy as np

In [6]:
sales = np.random.randint(10, size=(5,3))
prices = np.random.randint(5, size=(3))

In [8]:
sales, prices

(array([[6, 9, 5],
        [9, 3, 6],
        [5, 7, 9],
        [0, 1, 8],
        [7, 2, 6]]),
 array([3, 2, 0]))

In [9]:
sales_df = pd.DataFrame(
    sales,
    index=["Mon", "Tue", "Wed", "Thu", "Fri"],
    columns=["Gameboy", "Wii", "Switch"]
)
sales_df

Gameboy  Wii  Switch
Mon        6    9       5
Tue        9    3       6
Wed        5    7       9
Thu        0    1       8
Fri        7    2       6

In [10]:
prices_df = pd.DataFrame(
    prices.reshape(1,3),
    index=["Prices"],
    columns=["Gameboy", "Wii", "Switch"]
)
prices_df

Gameboy  Wii  Switch
Prices        3    2       0

Now we want to use the prices DataFrame and multiply it with the sales DataFrame to figure out how much money we made on a particular day using the `dot product`.

In [31]:
total_sales_matrix = np.dot(prices, sales.T)
total_sales_matrix

array([56, 30, 19, 25,  3])

In [36]:
daily_sales_df = prices_df.dot(sales_df.T)
daily_sales_df.T

Prices
Mon      56
Tue      30
Wed      19
Thu      25
Fri       3

Finally, we want to add the total amount of money on a particular as a new column to our sales Dataframe.

In [38]:
sales_df["Total ($)"] = daily_sales_df.T
sales_df

Gameboy  Wii  Switch  Total ($)
Mon        3    8       8         56
Tue        8    2       6         30
Wed        7    1       4         19
Thu        3    7       1         25
Fri        0    1       0          3