## Comparison Operators

In [1]:
import numpy as np

In [4]:
smaller = np.random.randint(5, size=(3))
larger = np.random.randint(10, size=(5,3))
smaller, larger

(array([1, 4, 1]),
 array([[0, 3, 4],
        [6, 6, 1],
        [5, 0, 5],
        [6, 0, 2],
        [0, 1, 8]]))

In [5]:
smaller > larger

array([[ True,  True, False],
       [False, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True,  True, False]])

In [6]:
smaller >= larger

array([[ True,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [ True,  True, False]])

In [7]:
smaller == larger

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

## Sorting Arrays

In [9]:
random = np.random.randint(10, size=(3,5))
random

array([[3, 9, 9, 3, 9],
       [5, 3, 2, 7, 4],
       [8, 7, 6, 3, 3]])

In [10]:
np.sort(random)

array([[3, 3, 9, 9, 9],
       [2, 3, 4, 5, 7],
       [3, 3, 6, 7, 8]])

Sort the index of the arrays

In [12]:
np.argsort(random)

array([[0, 3, 1, 2, 4],
       [2, 1, 4, 0, 3],
       [3, 4, 2, 1, 0]])

In [14]:
np.argmin(random), np.argmax(random)

(7, 1)

In [15]:
np.argmax(random, axis=1)

array([1, 3, 0])