## Comparison Operators

In [1]:
import numpy as np

In [4]:
smaller = np.random.randint(5, size=(3))
larger = np.random.randint(10, size=(5,3))
smaller, larger

(array([1, 4, 1]),
 array([[0, 3, 4],
        [6, 6, 1],
        [5, 0, 5],
        [6, 0, 2],
        [0, 1, 8]]))

In [5]:
smaller > larger

array([[ True,  True, False],
       [False, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True,  True, False]])